### ISSUE TITLE
Mailing list issues

### ISSUE THREAD

**Issue by doorsdown** [libssh2/www#11]
I send an email to the mailing list on early Thursday morning about #10 but it has still let to come thru. I've provided the top of the message info that gmail has on this.

> MIME-Version: 1.0
Date: Thu, 18 Apr 2019 00:16:55 -0400
Message-ID: <CAL627UuytH5AnRg4iqaksnGSd6YNkz669=HZb_kvpXqOxLkjTA@mail.gmail.com>
Subject: API/Docs Link Dead
From: Ryan Kelley <ryan.parker.kelley@gmail.com>
To: libssh2-devel@cool.haxx.se

**Comment by bagder** [comment]
You must be subscribed to the list with the same email address that you're sending from, and this email address is not currently subscribed.

I've now added a clear mention about this requirement.
