### ISSUE TITLE
https://libssh2.org/libssh2-vs-libssh.html → 404

### ISSUE THREAD

**Issue by vszakats** [libssh2/www#23]
After pushing two minor updates to `libssh2-vs-libssh.t`:
https://github.com/libssh2/www/commit/7f64f822399de8074c94ba3cf7fc9dd4dce861dd
https://github.com/libssh2/www/commit/b034dd0130a6add7aa4552aee1594e1e854a4c41

the rendered page no longer exists on the server:
https://libssh2.org/libssh2-vs-libssh.html

```
Not Found

The requested URL was not found on this server.
```

What could have happened?

**Comment by bagder** [comment]
Odd. I ran the same operation manually on the server just now and then it built it fine. I'll dig a little more and see if I can figure it out.
